### ISSUE TITLE
class Grid

### ISSUE THREAD

**Issue by michaelscheinfeild** [Lotemn102/Ball-Pivoting-Algorithm#9]
you try to make encoding of x,y,z to index but all  -1<x_cell,y_cell,z_cell <1
so all the code are zero
 code = utils.encode_cell(x=x_cell, y=y_cell, z=z_cell)

 code = x | (y << 8) | (z << 16)

**Comment by Lotemn102** [comment]
The value of `code` is 0 if `x=0` and `y=0` and `z=0`.
Can you provide an example?
